'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''pnlAccountSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccountSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''plRolename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plRolename As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''cboRolename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRolename As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvRolename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRolename As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''plDefaultUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDefaultUsername As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''cboUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUsername As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''plAutoLoginDefaultEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAutoLoginDefaultEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkAutoLoginDefaultEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAutoLoginDefaultEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plAccountSwitchEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAccountSwitchEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkAccountSwitchEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAccountSwitchEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plForceLoginDefaultEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plForceLoginDefaultEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkForceLoginDefaultEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForceLoginDefaultEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlUrlLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUrlLogin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''plUrlLoginEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plUrlLoginEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkUrlLoginEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUrlLoginEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlVisibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVisibility As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''plIsModuleVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIsModuleVisible As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkIsModuleVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsModuleVisible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlControlAccessByIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlControlAccessByIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''plIPRestrictionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIPRestrictionMode As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''cboIPRestrictionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboIPRestrictionMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plIPAddressList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIPAddressList As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtIPAddressList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIPAddressList As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plIPRestrictionEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIPRestrictionEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkIPRestrictionEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIPRestrictionEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plIPDisplayEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIPDisplayEnable As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkIPDisplayEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIPDisplayEnable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlRecordKeeping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecordKeeping As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSetupNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetupNote As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtSetupNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSetupNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lblLastUpdateDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateDisplay As Global.System.Web.UI.WebControls.Label
End Class
